### ISSUE TITLE
Error running the app

### ISSUE THREAD

**Issue by raultomescu** [SvitlanaShepitsena/itsquiz-wall#12]
When I do `npm run nodemon` I get

```
Error: Cannot find module '../../etc/no-share.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/server/config/secrets.js:9:23)
    at Module._compile (module.js:398:26)
    at normalLoader (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/server/config/passport/google.js:4:15)
    at Module._compile (module.js:398:26)
    at normalLoader (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/raul/Desktop/GitHubProjects/itsquiz-wall-svitlana/itsquiz-wall/node_modules/babel-core/lib/api/register/node.js:216:7)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by AndriyShepitsen** [comment]
Thank you, Raul. Readme is updated with instructions how to handle the issue.
Now Google+ auth is working. Fb is being developed right now :-)
